baseurl = "/"
languageCode = "pt-br"
title = "Bruna Wundervald"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Bruna Wundervald"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "brunaw"
  Email         = "bruna.daviesw@gmail.com"
 
## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "GitHub"
  weight = 100
  identifier = "GitHub"
  url = "http://github.com/brunaw"
[[menu.main]]
  name = "Projetos"
  identifier = "Projetos"
  weight = 200
  url = "/Projetos/"
[[menu.main]]
  name = "Lattes"
  identifier = "Lattes"
  weight = 300
  url = "http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K8105709Z2"
